### ISSUE TITLE
Incorrect transformers version

### ISSUE THREAD

**Issue by MikkoMMM** [AIDungeonWiXAnon/AID2-Installer-Project#2]
Clover Edition (at least currently) requires a very specific transformers version (2.3.0), which this installer doesn't seem to download. This has resulted in these tickets in Clover's repository:

https://github.com/cloveranon/Clover-Edition/issues/129
https://github.com/cloveranon/Clover-Edition/issues/132

**Comment by AIDungeonWiXAnon** [comment]
Looks like pip updated its repository version of transformers; I'll edit the installer to force 2.3.0, thanks for bringing this to my attention.
